import canard_solutions_ordinary_differential_equations_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace canard_solutions_ordinary_differential_equations_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end canard_solutions_ordinary_differential_equations_theorem_canonical_lane_mathlib
end HautevilleHouse
